keys:
  - &nyx_down age1l60m6fq86rfgxjwl3yfg64tp5fc7322wwzypvt6w7n9ughh88spsqgesp5
  - &host_down age1aycn5qk486p5te332u53wdzl2y9rev7wfjm65d2zffgfz9hjesrsanact9
  - &host_top age1aycn5qk486p5te332u53wdzl2y9rev7wfjm65d2zffgfz9hjesrsanact9
  - &host_neutrino age12vd83kucdn27affre6sekpe89g8yy5kxp0xyauyd4nxm8kr4tcfsu7yeaj
  - &host2_top age15l7s7ushkew7a2ltq0zuayj5j0dzl5e00k840ndluty469nvsu3qg9z2vc
  - &host_antidown age1ef9x5gqzf06srhw9vxeh6qplkpvpsk8uccnuhdcwe4s8gmm8sq2swlwga3

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *nyx_down
          - *host_down
          - *host_top
          - *host_neutrino
          - *host_antidown
          - *host2_top
