keys:
  - &nyx_down age1l60m6fq86rfgxjwl3yfg64tp5fc7322wwzypvt6w7n9ughh88spsqgesp5
  - &host_down age1aycn5qk486p5te332u53wdzl2y9rev7wfjm65d2zffgfz9hjesrsanact9
  - &host_top age1aycn5qk486p5te332u53wdzl2y9rev7wfjm65d2zffgfz9hjesrsanact9
  - &host_neutrino age12vd83kucdn27affre6sekpe89g8yy5kxp0xyauyd4nxm8kr4tcfsu7yeaj
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *nyx_down
          - *host_down
          - *host_top
          - *host_neutrino
